name: stackfood
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  device_info_plus: ^11.2.2
  android_id: ^0.4.0
  package_info_plus: ^8.1.4
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  get_it: ^8.0.3
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/